int scan_error(float a, float b, char c);
void print(float ans, int i);
int search_i(float a, float b);
int search_j(int i);
float search_x(float a, int j1, float j2);
float search_y(float b, int j1, float j2);
float sum(float x, float y);
float difference(float x, float y);
float mult(float a, float b);
float division(float a, float b);
int remainde(int x, int y);